# global environment of current service
env: dev  

# naming of current service
app:
  name: xvibe-message-gateway
  version: v0.0.1

# settings of server's runner
server:
  http:
    host: 0.0.0.0
    port: 7082
    # tls config
    tls:
      enable: true
      server-cert: ./certs/server.crt
      server-key: ./certs/server.key
  read-timeout: 2s
  write-timeout: 2s
  idle-timeout: 30s

# dependencies
services:
  xvibe-message:
    host: xvibe-message-service
    port: 50052
    # mtls config
    tls: 
      enable: true
      client-cert: ./gateway-certs/client.crt
      client-key: ./gateway-certs/client.key
      ca-cert: ./gateway-certs/rootCA.pem