# global enironment of current service
env: dev

# naming of current service
app:
  name: xvibe-message-service
  version: v0.0.1

# settings of server's runner
server:
  grpc:
    host: 0.0.0.0
    port: 50052
    protocol: tcp
    # settings of tls
    tls:
      enable: true
      server-cert: ./certs/server.crt
      server-key: ./certs/server.key
      ca-cert: ./certs/rootCA.pem
  # request's timeout
  timeout: 2s

# settings of external services
services:
  xvibe-auth:
    host: xvibe-auth-service
    port: 50050
    tls:
      enable: true
      client-cert: ./client-certs/client.crt
      client-key: ./client-certs/client.key
      ca-cert: ./client-certs/rootCA.pem

# secrets
secrets:
  cipher:
    nonce-size: 12
  
  postgres:
    host: postgres
    port: 5432
    sslmode: disable
    auth:
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      dbname: ${POSTGRES_DBNAME}
    conn:
      max-idles: 15
      max-opens: 5
      max-lifetime: 5m
      max-idle-time: 30m
  
  redis:
    host: redis
    port: 6379
    auth:
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      db: ${REDIS_DB}
    
  jwt:
    public-key-path: ./jwtRS256.key.pub