mkcertlocal:
	mkcert -install
	mkcert xvibe-rl localhost 127.0.0.1
	
	mkdir ./certs/
	mv xvibe-rl+2.pem server.crt
	mv ./server.crt ./certs/
	mv xvibe-rl+2-key.pem server.key 
	mv ./server.key ./certs/
