// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: chat/v1/chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chat_Create_FullMethodName        = "/chat.v1.Chat/Create"
	Chat_Delete_FullMethodName        = "/chat.v1.Chat/Delete"
	Chat_UpdateGroup_FullMethodName   = "/chat.v1.Chat/UpdateGroup"
	Chat_AddMembers_FullMethodName    = "/chat.v1.Chat/AddMembers"
	Chat_DeleteMembers_FullMethodName = "/chat.v1.Chat/DeleteMembers"
	Chat_GetSelfChats_FullMethodName  = "/chat.v1.Chat/GetSelfChats"
	Chat_GetChat_FullMethodName       = "/chat.v1.Chat/GetChat"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	// Create a new chat
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ChatModel, error)
	// Delete the chat (soft-delete)
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user (group can be deleted only by owner)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Update the chat of group
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user
	UpdateGroup(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ChatWithMembers, error)
	// Add members into group
	// REQUIRES: mtls connection with gateway
	AddMembers(ctx context.Context, in *MembersRequest, opts ...grpc.CallOption) (*ChatWithMembers, error)
	// Delete members from group
	// REQUIRES: mtls connection with gateway
	DeleteMembers(ctx context.Context, in *MembersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get all chats by jwt-token
	// Returns up to 100 chats. No pagination needed in MVP.
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user
	GetSelfChats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ChatModels, error)
	// GetGroup with members
	// REQUIRES: mtls connection with gateway
	GetChat(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ChatWithMembers, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ChatModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatModel)
	err := c.cc.Invoke(ctx, Chat_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Chat_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) UpdateGroup(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ChatWithMembers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatWithMembers)
	err := c.cc.Invoke(ctx, Chat_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) AddMembers(ctx context.Context, in *MembersRequest, opts ...grpc.CallOption) (*ChatWithMembers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatWithMembers)
	err := c.cc.Invoke(ctx, Chat_AddMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) DeleteMembers(ctx context.Context, in *MembersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Chat_DeleteMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetSelfChats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ChatModels, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatModels)
	err := c.cc.Invoke(ctx, Chat_GetSelfChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetChat(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ChatWithMembers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatWithMembers)
	err := c.cc.Invoke(ctx, Chat_GetChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility.
type ChatServer interface {
	// Create a new chat
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user
	Create(context.Context, *CreateRequest) (*ChatModel, error)
	// Delete the chat (soft-delete)
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user (group can be deleted only by owner)
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// Update the chat of group
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user
	UpdateGroup(context.Context, *UpdateRequest) (*ChatWithMembers, error)
	// Add members into group
	// REQUIRES: mtls connection with gateway
	AddMembers(context.Context, *MembersRequest) (*ChatWithMembers, error)
	// Delete members from group
	// REQUIRES: mtls connection with gateway
	DeleteMembers(context.Context, *MembersRequest) (*emptypb.Empty, error)
	// Get all chats by jwt-token
	// Returns up to 100 chats. No pagination needed in MVP.
	// REQUIRES: mtls connection with gateway
	// METADATA: jwt-token of user
	GetSelfChats(context.Context, *emptypb.Empty) (*ChatModels, error)
	// GetGroup with members
	// REQUIRES: mtls connection with gateway
	GetChat(context.Context, *GetRequest) (*ChatWithMembers, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) Create(context.Context, *CreateRequest) (*ChatModel, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedChatServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChatServer) UpdateGroup(context.Context, *UpdateRequest) (*ChatWithMembers, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedChatServer) AddMembers(context.Context, *MembersRequest) (*ChatWithMembers, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMembers not implemented")
}
func (UnimplementedChatServer) DeleteMembers(context.Context, *MembersRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMembers not implemented")
}
func (UnimplementedChatServer) GetSelfChats(context.Context, *emptypb.Empty) (*ChatModels, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSelfChats not implemented")
}
func (UnimplementedChatServer) GetChat(context.Context, *GetRequest) (*ChatWithMembers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}
func (UnimplementedChatServer) testEmbeddedByValue()              {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	// If the following call panics, it indicates UnimplementedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).UpdateGroup(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_AddMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).AddMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_AddMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).AddMembers(ctx, req.(*MembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_DeleteMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).DeleteMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_DeleteMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).DeleteMembers(ctx, req.(*MembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetSelfChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetSelfChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_GetSelfChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetSelfChats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetChat(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.v1.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Chat_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Chat_Delete_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _Chat_UpdateGroup_Handler,
		},
		{
			MethodName: "AddMembers",
			Handler:    _Chat_AddMembers_Handler,
		},
		{
			MethodName: "DeleteMembers",
			Handler:    _Chat_DeleteMembers_Handler,
		},
		{
			MethodName: "GetSelfChats",
			Handler:    _Chat_GetSelfChats_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _Chat_GetChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat/v1/chat.proto",
}
