// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: chat/v1/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_UNKNOWN Type = 0
	Type_TYPE_SELF    Type = 1
	Type_TYPE_GROUP   Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_SELF",
		2: "TYPE_GROUP",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"TYPE_SELF":    1,
		"TYPE_GROUP":   2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_chat_v1_chat_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

// Domain model of this service
type ChatModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"` // can be empty if typ == TYPE_SELF
	Typ           Type                   `protobuf:"varint,4,opt,name=typ,proto3,enum=chat.v1.Type" json:"typ,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatModel) Reset() {
	*x = ChatModel{}
	mi := &file_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatModel) ProtoMessage() {}

func (x *ChatModel) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatModel.ProtoReflect.Descriptor instead.
func (*ChatModel) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatModel) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ChatModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChatModel) GetTyp() Type {
	if x != nil {
		return x.Typ
	}
	return Type_TYPE_UNKNOWN
}

func (x *ChatModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ChatModels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatModel           `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatModels) Reset() {
	*x = ChatModels{}
	mi := &file_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatModels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatModels) ProtoMessage() {}

func (x *ChatModels) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatModels.ProtoReflect.Descriptor instead.
func (*ChatModels) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatModels) GetChats() []*ChatModel {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ChatModels) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	IsOwner       bool                   `protobuf:"varint,4,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Member) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *Member) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type ChatWithMembers struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Chat           *ChatModel             `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	MemberIds      []*Member              `protobuf:"bytes,2,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	IsCurrentOwner bool                   `protobuf:"varint,3,opt,name=is_current_owner,json=isCurrentOwner,proto3" json:"is_current_owner,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatWithMembers) Reset() {
	*x = ChatWithMembers{}
	mi := &file_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatWithMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatWithMembers) ProtoMessage() {}

func (x *ChatWithMembers) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatWithMembers.ProtoReflect.Descriptor instead.
func (*ChatWithMembers) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatWithMembers) GetChat() *ChatModel {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *ChatWithMembers) GetMemberIds() []*Member {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *ChatWithMembers) GetIsCurrentOwner() bool {
	if x != nil {
		return x.IsCurrentOwner
	}
	return false
}

func (x *ChatWithMembers) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroup) Reset() {
	*x = CreateGroup{}
	mi := &file_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroup) ProtoMessage() {}

func (x *CreateGroup) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroup.ProtoReflect.Descriptor instead.
func (*CreateGroup) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateGroup) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateSelf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// member_id must be different from the authenticated user's ID
	MemberId      string `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"` // another member will be taken from token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSelf) Reset() {
	*x = CreateSelf{}
	mi := &file_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelf) ProtoMessage() {}

func (x *CreateSelf) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelf.ProtoReflect.Descriptor instead.
func (*CreateSelf) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSelf) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Typ   Type                   `protobuf:"varint,1,opt,name=typ,proto3,enum=chat.v1.Type" json:"typ,omitempty"`
	// Types that are valid to be assigned to Creates:
	//
	//	*CreateRequest_CreateGroup
	//	*CreateRequest_CreateSelf
	Creates       isCreateRequest_Creates `protobuf_oneof:"creates"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRequest) GetTyp() Type {
	if x != nil {
		return x.Typ
	}
	return Type_TYPE_UNKNOWN
}

func (x *CreateRequest) GetCreates() isCreateRequest_Creates {
	if x != nil {
		return x.Creates
	}
	return nil
}

func (x *CreateRequest) GetCreateGroup() *CreateGroup {
	if x != nil {
		if x, ok := x.Creates.(*CreateRequest_CreateGroup); ok {
			return x.CreateGroup
		}
	}
	return nil
}

func (x *CreateRequest) GetCreateSelf() *CreateSelf {
	if x != nil {
		if x, ok := x.Creates.(*CreateRequest_CreateSelf); ok {
			return x.CreateSelf
		}
	}
	return nil
}

type isCreateRequest_Creates interface {
	isCreateRequest_Creates()
}

type CreateRequest_CreateGroup struct {
	CreateGroup *CreateGroup `protobuf:"bytes,2,opt,name=create_group,json=createGroup,proto3,oneof"`
}

type CreateRequest_CreateSelf struct {
	CreateSelf *CreateSelf `protobuf:"bytes,3,opt,name=create_self,json=createSelf,proto3,oneof"`
}

func (*CreateRequest_CreateGroup) isCreateRequest_Creates() {}

func (*CreateRequest_CreateSelf) isCreateRequest_Creates() {}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type MembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersRequest) Reset() {
	*x = MembersRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersRequest) ProtoMessage() {}

func (x *MembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersRequest.ProtoReflect.Descriptor instead.
func (*MembersRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *MembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MembersRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

var File_chat_v1_chat_proto protoreflect.FileDescriptor

const file_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x12chat/v1/chat.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa8\x01\n" +
	"\tChatModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\x03typ\x18\x04 \x01(\x0e2\r.chat.v1.TypeR\x03typ\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"p\n" +
	"\n" +
	"ChatModels\x12(\n" +
	"\x05chats\x18\x01 \x03(\v2\x12.chat.v1.ChatModelR\x05chats\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"v\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x19\n" +
	"\bis_owner\x18\x04 \x01(\bR\aisOwner\"\xcd\x01\n" +
	"\x0fChatWithMembers\x12&\n" +
	"\x04chat\x18\x01 \x01(\v2\x12.chat.v1.ChatModelR\x04chat\x12.\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\v2\x0f.chat.v1.MemberR\tmemberIds\x12(\n" +
	"\x10is_current_owner\x18\x03 \x01(\bR\x0eisCurrentOwner\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"B\n" +
	"\vCreateGroup\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\tR\tmemberIds\")\n" +
	"\n" +
	"CreateSelf\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\xae\x01\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\x03typ\x18\x01 \x01(\x0e2\r.chat.v1.TypeR\x03typ\x129\n" +
	"\fcreate_group\x18\x02 \x01(\v2\x14.chat.v1.CreateGroupH\x00R\vcreateGroup\x126\n" +
	"\vcreate_self\x18\x03 \x01(\v2\x13.chat.v1.CreateSelfH\x00R\n" +
	"createSelfB\t\n" +
	"\acreates\">\n" +
	"\rUpdateRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"(\n" +
	"\rDeleteRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"H\n" +
	"\x0eMembersRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\tR\tmemberIds\"%\n" +
	"\n" +
	"GetRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId*7\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\r\n" +
	"\tTYPE_SELF\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_GROUP\x10\x022\xb1\x03\n" +
	"\x04Chat\x124\n" +
	"\x06Create\x12\x16.chat.v1.CreateRequest\x1a\x12.chat.v1.ChatModel\x128\n" +
	"\x06Delete\x12\x16.chat.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\vUpdateGroup\x12\x16.chat.v1.UpdateRequest\x1a\x18.chat.v1.ChatWithMembers\x12?\n" +
	"\n" +
	"AddMembers\x12\x17.chat.v1.MembersRequest\x1a\x18.chat.v1.ChatWithMembers\x12@\n" +
	"\rDeleteMembers\x12\x17.chat.v1.MembersRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\fGetSelfChats\x12\x16.google.protobuf.Empty\x1a\x13.chat.v1.ChatModels\x128\n" +
	"\aGetChat\x12\x13.chat.v1.GetRequest\x1a\x18.chat.v1.ChatWithMembersB'Z%github.com/devathh/xvibe/chat; chatpbb\x06proto3"

var (
	file_chat_v1_chat_proto_rawDescOnce sync.Once
	file_chat_v1_chat_proto_rawDescData []byte
)

func file_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_v1_chat_proto_rawDesc), len(file_chat_v1_chat_proto_rawDesc)))
	})
	return file_chat_v1_chat_proto_rawDescData
}

var file_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chat_v1_chat_proto_goTypes = []any{
	(Type)(0),                     // 0: chat.v1.Type
	(*ChatModel)(nil),             // 1: chat.v1.ChatModel
	(*ChatModels)(nil),            // 2: chat.v1.ChatModels
	(*Member)(nil),                // 3: chat.v1.Member
	(*ChatWithMembers)(nil),       // 4: chat.v1.ChatWithMembers
	(*CreateGroup)(nil),           // 5: chat.v1.CreateGroup
	(*CreateSelf)(nil),            // 6: chat.v1.CreateSelf
	(*CreateRequest)(nil),         // 7: chat.v1.CreateRequest
	(*UpdateRequest)(nil),         // 8: chat.v1.UpdateRequest
	(*DeleteRequest)(nil),         // 9: chat.v1.DeleteRequest
	(*MembersRequest)(nil),        // 10: chat.v1.MembersRequest
	(*GetRequest)(nil),            // 11: chat.v1.GetRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_chat_v1_chat_proto_depIdxs = []int32{
	0,  // 0: chat.v1.ChatModel.typ:type_name -> chat.v1.Type
	12, // 1: chat.v1.ChatModel.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chat.v1.ChatModels.chats:type_name -> chat.v1.ChatModel
	12, // 3: chat.v1.ChatModels.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 4: chat.v1.ChatWithMembers.chat:type_name -> chat.v1.ChatModel
	3,  // 5: chat.v1.ChatWithMembers.member_ids:type_name -> chat.v1.Member
	12, // 6: chat.v1.ChatWithMembers.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 7: chat.v1.CreateRequest.typ:type_name -> chat.v1.Type
	5,  // 8: chat.v1.CreateRequest.create_group:type_name -> chat.v1.CreateGroup
	6,  // 9: chat.v1.CreateRequest.create_self:type_name -> chat.v1.CreateSelf
	7,  // 10: chat.v1.Chat.Create:input_type -> chat.v1.CreateRequest
	9,  // 11: chat.v1.Chat.Delete:input_type -> chat.v1.DeleteRequest
	8,  // 12: chat.v1.Chat.UpdateGroup:input_type -> chat.v1.UpdateRequest
	10, // 13: chat.v1.Chat.AddMembers:input_type -> chat.v1.MembersRequest
	10, // 14: chat.v1.Chat.DeleteMembers:input_type -> chat.v1.MembersRequest
	13, // 15: chat.v1.Chat.GetSelfChats:input_type -> google.protobuf.Empty
	11, // 16: chat.v1.Chat.GetChat:input_type -> chat.v1.GetRequest
	1,  // 17: chat.v1.Chat.Create:output_type -> chat.v1.ChatModel
	13, // 18: chat.v1.Chat.Delete:output_type -> google.protobuf.Empty
	4,  // 19: chat.v1.Chat.UpdateGroup:output_type -> chat.v1.ChatWithMembers
	4,  // 20: chat.v1.Chat.AddMembers:output_type -> chat.v1.ChatWithMembers
	13, // 21: chat.v1.Chat.DeleteMembers:output_type -> google.protobuf.Empty
	2,  // 22: chat.v1.Chat.GetSelfChats:output_type -> chat.v1.ChatModels
	4,  // 23: chat.v1.Chat.GetChat:output_type -> chat.v1.ChatWithMembers
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chat_v1_chat_proto_init() }
func file_chat_v1_chat_proto_init() {
	if File_chat_v1_chat_proto != nil {
		return
	}
	file_chat_v1_chat_proto_msgTypes[6].OneofWrappers = []any{
		(*CreateRequest_CreateGroup)(nil),
		(*CreateRequest_CreateSelf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_v1_chat_proto_rawDesc), len(file_chat_v1_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_chat_v1_chat_proto = out.File
	file_chat_v1_chat_proto_goTypes = nil
	file_chat_v1_chat_proto_depIdxs = nil
}
