# global enironment of this service
env: dev

# naming of this service
app:
  name: xvibe-auth-gateway
  version: v0.0.1

# settings of server
server:
  http:
    host: 0.0.0.0
    port: 7080
    # tls config
    tls:
      enable: true
      server-cert: ./certs/server.crt
      server-key: ./certs/server.key
  read-timeout: 2s
  write-timeout: 2s
  idle-timeout: 30s

# under-hood service settings
services:
  xvibe-auth:
    host: xvibe-auth-service
    port: 50050
    mtls:
      enable: true
      client-cert: ./client-certs/client.crt
      client-key: ./client-certs/client.key
      ca-cert: ./client-certs/rootCA.pem