# global environment
env: dev

# naming of current service
app:
  name: xvibe-chat-service
  version: v0.0.1

# settings of server's runner
server:
  grpc:
    host: 0.0.0.0
    port: 50051
    protocol: tcp
    # tls config
    tls:
      enable: true
      server-cert: ./certs/server.crt
      server-key: ./certs/server.key
      ca-cert: ./certs/rootCA.pem
  # request's timeout
  timeout: 2s

# service's settings (ex. cache ttl)
service:
  cache:
    chats-ttl: 5m

# settings of external services
services:
  xvibe-auth:
    host: xvibe-auth-service
    port: 50050
    tls:
      enable: true
      client-cert: ./client-certs/client.crt
      client-key: ./client-certs/client.key
      ca-cert: ./client-certs/rootCA.pem

# secrets is taken from .env
secrets:
  postgres:
    host: postgres
    port: 5432
    sslmode: disable
    auth:
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      dbname: ${POSTGRES_DBNAME}
    conn:
      max-idles: 30
      max-opens: 15
      max-lifetime: 15m
      max-idle-time: 30m
  
  redis:
    host: redis
    port: 6379
    auth:
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      db: ${REDIS_DB}

  jwt:
    public-key-path: ./jwtRS256.key.pub
  
  cipher:
    nonce-size: 12
    